auth0-extensions/auth0-source-control-extension-tools

src/auth0/connections.js, src/auth0/rules.js, src/deploy.js, src/utils.js, tests/utils.tests.js
Reduces the script file's from being logged.  This fixes issue #11.
Instead of logging the file a checksum is being generated and logged instead.  There is no need to log the contents of rules and database connection's action scripts.
=> Stop logging connection and rule files

package.json, src/utils.js
Webtasks run on node v4 and this code assumes node v6+.  converting Array.prototype.includes to Array.prototype.indexOf.
=> Fixing bug by removing Array.includes and replacing with Array.indexOf

src/constants.js
Adding get_user to db connection scripts when import users is false
Fixes Issue #15 
** Note: i didn't bump the version or test this out.  I didn't have time, however I added this as a starting point as it seems an easy fix.
=> Fixing #15

src/utils.js, tests/auth0/connections.tests.js, tests/utils.tests.js
There have been some requests for the ability to do a keyword
replacement within a string.  This restricts that ability to do full
JSON replacements, so adding a new way to pass mappings in that allow
for separation of simple and json mappings.
Also added some better error reporting for bad JSON files.  The error
message was previously getting squashed and it wasn't printing the
post-keyword replacement JSON.  Now it prints the error message right,
and adds the post-replacement JSON.  So you can compare pre and post.
@sandrinodimattia which team am I supposed to bug for PR's on this repo now?
=> Add support for simple keyword replacement.

package.json, src/auth0/rules.js, tests/auth0/rules.tests.js
The use case presented is that there are rules that they might want to have deployed to dev, but not to production or vice versa.
=> Add the ability to exclude new rules by including them in the list of rules

src/storage.js
Currently, we're saving too much data to the wt storage. Even last 10 deployments may reach storage limits in case of large rules, as we're saving entire rule code. So i'd suggest to trim big scripts, before saving them to the storage.
What do you think?
=> Trim big scripts before saving

package.json, src/storage.js, tests/storage.tests.js
This is an attempt to further mitigate the likelihood the deployment history will exceed the 500K storage limits.  This PR will remove the oldest history records until there is enough space to store the most recent record.  If the newest record will exceed the maximum storage size in its own right most of the blob data will be removed.  The new schema will look something like this:
```
var progress = {
id: 1,
user: 2,
branch: 3,
repository: 4,
date: 5,
connectionsUpdated: 6,
rulesCreated: 7,
rulesUpdated: 8,
rulesDeleted: 9,
error: 10,
message: 'This log entry has exceeded the maximum allowed size and data has been redacted to reduce the total size.'
};
```
The remaining data should preserve some useful details, but will surely remove the variable sized data ensuring it will not, on its …
=> Prevent history from exceeding 500KB

package.json, src/auth0/handlers/clientGrants.js, src/auth0/handlers/clients.js, src/auth0/handlers/connections.js, src/auth0/handlers/databases.js, src/utils.js, tests/auth0/handlers/clientGrants.tests.js, tests/auth0/handlers/clients.tests.js, tests/auth0/handlers/connections.tests.js, tests/auth0/handlers/databases.tests.js, tests/utils.tests.js
Minor updates to fix the following
- Leave the client_id to client_name dump conversation to auth0-deploy-cli
- Fix client grants not being detected for updates properly (had to allow for grouped identifiers)
- Filter out the deploy client on clients.processChanges vs getType thus allowing the client to flow through to Auth0-deploy-cli
All tests updated.   
=> Fix client grants

package-lock.json, package.json, src/auth0/handlers/guardianFactorProviders.js, src/auth0/handlers/guardianFactorTemplates.js, src/auth0/handlers/guardianFactors.js, src/auth0/handlers/index.js, src/auth0/handlers/rules.js, src/constants.js, tests/auth0/handlers/guardianFactorProviders.tests.js, tests/auth0/handlers/guardianFactorTemplates.tests.js, tests/auth0/handlers/guardianFactors.tests.js
This change adds guardian Factors, Provider and Templates support.
Built in a generic way for when new factors or providers come into play.
Depends on 
https://github.com/auth0/node-auth0/pull/311
https://github.com/auth0/node-auth0/pull/315
🚫 Waiting on node-auth0 release before merge
=> Add guardian support

README.md, package-lock.json, package.json, src/auth0/handlers/default.js, src/auth0/handlers/rules.js, tests/auth0/handlers/clients.tests.js, tests/utils.tests.js
The packages `auth0` and `auth0-auth2-express` were flagged with high risk security vulnerabilities. But they were unused.
All unused dependencies that were flagged by `depcheck` was removed and the suggested ones installed.
Also ran `eslint --fix` on other files.
Jira: https://auth0team.atlassian.net/browse/KEY-504
=> KEY-504: Clean up packages and remove insecure packages

package.json, src/auth0/handlers/databases.js, tests/auth0/handlers/databases.tests.js
API2 does not preserve old options properties on connection update. That's why we need to get old options object and merge it with new options before update.
Jira: https://auth0team.atlassian.net/browse/KEY-639
✅ This change has been tested in a Webtask
=> KEY-639: connection prop reset

src/auth0/handlers/databases.js, tests/auth0/handlers/databases.tests.js
Currently, we're forcing `enabled_clients` setting of the database connection to be updated, even if we do not have such setting in the assets (using `[]` by default). In these changes additional check is added to prevent updating `enabled_clients` if the list of enabled clients was not provided in the assets.
Slack: https://auth0.slack.com/archives/C9170558S/p1545937917007200?thread_ts=1544222234.120100&cid=C9170558S
✅ This change has been tested locally
=> Do not force `enabled_clients` setting

src/auth0/handlers/databases.js
Error in latest update with where import_mode is required. It's meant to be required under options. 
Fixes below error
```
{
"keyword": "required",
"dataPath": ".databases[0]",
"schemaPath": "#/properties/databases/items/required",
"params": {
"missingProperty": ".import_mode"
},
"message": "should have required property '.import_mode'"
}
```
=> Fix error due to import_mode required at wrong level

src/auth0/handlers/clientGrants.js, src/auth0/handlers/clients.js, src/auth0/handlers/connections.js, src/auth0/handlers/default.js, src/auth0/handlers/pages.js, src/auth0/handlers/resourceServers.js, src/auth0/handlers/rules.js
Allow `source-control-tools` to process empty arrays in order to remove all existing records from tenant. This change is meant to fix [auth0-deploy-cli issue #74](https://github.com/auth0/auth0-deploy-cli/issues/74). Deploy extensions are not yet ready to use tools with this change and those should remain on v3.1.4 of the `source-control-tools`.
GitHub Issue: https://github.com/auth0/auth0-deploy-cli/issues/74
This change has been tested locally with `auth0-deploy-cli`.
=> Key 686: process empty arrays

src/auth0/handlers/emailProvider.js
When exporting the emailProvider shows default values as we are not requesting the correct fields in the mgmt api.
This fixes https://github.com/auth0/auth0-deploy-cli/issues/84
=> Fix email provider export

src/auth0/handlers/clientGrants.js, tests/auth0/handlers/clientGrants.tests.js
Deploy extensions should not delete or update client grants of its own client. Currently, an attempt to update client grants of extension's client is leading to conflict error. Fixed by filtering client grants assets in similar way as we're doing for clients..
Slack: https://auth0.slack.com/archives/C9170558S/p1552574289164300
✅ This change has been tested locally (with Bitbucket extension)
=> Ignore client grants for own client

src/auth0/handlers/default.js, tests/auth0/handlers/clientGrants.tests.js, tests/auth0/handlers/clients.tests.js, tests/auth0/handlers/connections.tests.js, tests/auth0/handlers/databases.tests.js, tests/auth0/handlers/resourceServers.tests.js, tests/auth0/handlers/rules.tests.js
Tools won't delete rules without `ALLOW_DELETE` flag, which cannot be used in deploy-extensions, as it'll lead to removing clients, connections and other stuff as well. 
Extensions should be able to remove only rules/resourceServers.
GH Issue: https://github.com/auth0-extensions/auth0-deploy-extensions/issues/18
🚫 This change has been tested in a Webtask (need to be released and added to webtask first)
=> Allow extensions to remove rules/resourceServers

src/auth0/handlers/index.js, src/auth0/handlers/resourceServers.js, src/auth0/handlers/roles.js, src/constants.js, tests/auth0/handlers/roles.tests.js
> Adding roles handler for managing roles and permissions via the deploy-cli
> Added src/auth0/handlers/roles.js and tests/auth0/handlers/roles.tests.js, changed src/auth0/handlers/index.js and src/constants.js. Also changed src/auth0/handlers/resourceServers.j to add support for 2 new properties enforce_policies and token_dialect
> - Added unit tests for roles handler
> For roles functionality this change requires a new version of the node-auth0 package. `https://github.com/auth0/node-auth0`. Specifically …
=> Add support for roles and permissions for deploy-cli

src/auth0/handlers/emailProvider.js
The recent updates to emailProvider is showing sensitive data in logs during import.
This fixes https://github.com/auth0/auth0-deploy-cli/issues/97 by only showing the name and enabled flag in logs.
=> Hide emailProvider sensitive data in logs during import

package-lock.json, package.json, src/auth0/handlers/resourceServers.js, tests/auth0/handlers/resourceServers.tests.js
`identifier` of resource server cannot be changed. That means changing `identifier` in `tenant.yaml` has no effect (see https://github.com/auth0/auth0-deploy-cli/issues/129). Using `identifier` instead of `name` to identify resource server allows cli to create new api with desired `identifier` and, if ALLOW_DELETE is enabled, replace old api (with old `identifier`). Even if old api won't be deleted, `name` isn't unique, so we can have two apis with different identifiers but with same name.
GH issue: https://github.com/auth0/auth0-deploy-cli/issues/129
✅ This change has been tested in a locally
=>  calcChanges for resourceServers by 'identifier'

package-lock.json, package.json, src/auth0/handlers/clientGrants.js, src/auth0/handlers/connections.js, src/auth0/handlers/databases.js, tests/auth0/handlers/connections.tests.js, tests/auth0/handlers/databases.tests.js
Added filtering to remove excluded clients from connections (databases) `enabled_clients`.
Jira: https://auth0team.atlassian.net/browse/ESD-3190
=> ESD-3190: Excluded clients fix

package.json, src/auth0/handlers/hooks.js, src/auth0/handlers/roles.js, tests/auth0/handlers/hooks.tests.js, tests/auth0/handlers/roles.tests.js
Fixes to address multiple issues with auth0-deploy-cli when roles or hooks are not available due to tenant settings or unsupported APIs in environments.
* For roles, return empty arrays instead of objs to resolve `object not iterable` errors on import.
* For hooks, handle error status codes, specifically `403` in PSaaS envs, and return an empty array.
https://github.com/auth0/auth0-deploy-cli/issues/202
https://github.com/auth0-extensions/auth0-source-control-extension-tools/issues/78
Tested in environments with no roles and a disabled hooks API to replicate the errors and resolve. 
> Can this change be merged at any …
=> Continue processing if hooks or roles are not enabled

package-lock.json, package.json, src/auth0/handlers/hooks.js, tests/auth0/handlers/hooks.tests.js, tests/auth0/validator.tests.js
- hooks: support for post-change-password triggerId
- npm: audit fix, updated `auth0-extension-tools` to v1.4.4
N/A
Fixes #85
A hook with triggerId = `post-change-password` can be successfully created with an extension tool.
N/A
N/A
**Note to reviewers:** ensure that this change is compatible with the Appliance.
=> hooks: support for post-change-password triggerId

package.json, src/auth0/handlers/clientGrants.js, src/auth0/handlers/connections.js, src/auth0/handlers/databases.js, src/utils.js, tests/auth0/handlers/connections.tests.js, tests/utils.tests.js
For connections with `options.idpinitiated` property, we now support the client name being specified in `client_id` field. The `client_id` will be looked up in the client list and if there is a client's name matching the value, the corresponding `client_id` will be put into `client_id` before passing to the API for processing.
N/A
[ESD-4561](https://auth0team.atlassian.net/browse/ESD-4561)
1. No change to existing connection when replacing client ID with name in configuration:  
- Put a client's name in the `options.idpinitiated.client_id` property of an *existing* connection's configuration for `deploy-cli` or any supported deploy extensions
- Deploy using `deploy-cli` or a supported deploy extension
- No changes should be made to the deployed connection
2. Proper creation of new …
=> ESD-4561 IDP-initiated client_id translation

package-lock.json, package.json, src/auth0/handlers/rules.js, tests/auth0/handlers/rules.tests.js
When two rules with a different name but the same order collision, the reorder algorithm take the max order of all existing rules as the next available order for a rule, but this order could be the order of some of the new rules so when trying to create this set of rules they are rejected by `APIError: {"statusCode":409,"error":"Conflict","message":"A rule with the same order already exists","errorCode":"rule_conflict"}`
This fix takes into account both existing rules and new rules order to get the next available order in case of collision, assuring that that new order no exists as the order of existing rules or new rules. 
https://auth0team.atlassian.net/browse/ESD-3907
✅ This change has been tested in a Webtask
🚫 This change has integration test …
=> Esd 3907 fix rule ordering

src/auth0/client.js
We figured that github deployment was NOT always successful. Occasionally, we see that deployments got stuck at a point and did not recover itself. In many of those failures, we observed a role was updated, and yet its permissions were not added, which created a disastrous impact.
As advised by Thomas Osborn, the Auth0 Developer Support Engineer, it could be due to API rate limits.
https://support.auth0.com/tickets/00452451. We tested his principle by:
- Manually click "deploy" from the extension page
- Simultaneously, flood the management API from a laptop until it keeps resulting in "429 Too many requests"
- We observed from the Auth0 Webtask log that the deployment will be stuck, and will never complete.
Hence, we're proposing this PR to ensure a deployment will always work within a …
=> Improve deployment stability

src/auth0/handlers/hooks.js, tests/auth0/handlers/hooks.tests.js
- hooks: support for send-phone-message triggerId
N/A
Adding the send-phone-message trigger to support the new [MFA SMS Hook](https://auth0.com/docs/hooks/extensibility-points/send-phone-message)
A hook with triggerId = send-phone-message can be successfully created with an extension tool.
=> add `send-phone-message` triggerId for MFA SMS hook.

src/auth0/handlers/pages.js, tests/auth0/handlers/pages.tests.js, tests/auth0/validator.tests.js
Previously two properties of `error_page` type page were not defined in the schema for `pages`:
- `url`
- `show_log_link`
They are now added to the schema and test cases were added to ensure the validator can enforce the types.
N/A
- https://auth0team.atlassian.net/browse/DXEX-629
- Documentation on universal login error page: https://auth0.com/docs/universal-login/error-pages
- Management APIv2 explorer for tenant settings of `error_page`: https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings
In order to verify that the deployment was successful we will …
1. Specify `url` and …
=> [DXEX-629] validator: update schema for error_page in pages

package-lock.json, package.json, src/auth0/handlers/guardianPhoneFactorMessageTypes.js, src/auth0/handlers/guardianPhoneFactorSelectedProvider.js, src/auth0/handlers/guardianPolicies.js, src/auth0/handlers/index.js, src/constants.js, tests/auth0/handlers/guardianPhoneFactorMessageTypes.tests.js, tests/auth0/handlers/guardianPhoneFactorSelectedProvider.tests.js, tests/auth0/handlers/guardianPolicies.tests.js, tests/auth0/validator.tests.js
Add support for three guardian/MFA-related features:
- Guardian Policies
- Guardian Phone factor selected provider
- Guardian Phone factor message types
⚠️ Soft dependency on https://github.com/auth0/node-auth0/pull/501 (this PR is backwards compatible with older version of `node-auth0`)
🚫 
https://auth0team.atlassian.net/browse/MFA-311
This has been tested after being integrated with https://github.com/auth0/auth0-deploy-cli/pull/252.
=> [MFA-311] Support guardian policies, phone selected-provider and message-types

src/auth0/handlers/pages.js
Fixes: https://github.com/auth0/auth0-deploy-cli/issues/255
To reproduce:
- Install deploy-cli to latest version. Make sure that it installs the auth0-source-control-extension-tools to version 4.1.0 (released on July 2nd).
- Ensure your tenant has a custom `change_password` page.
- Export tenant settings
- Try to re-import tenant settings.
Error:
```
2020-07-06T18:08:20.319Z - error: Problem running command import during stage processChanges when processing type pages
2020-07-06T18:08:20.320Z - error: Payload validation error: 'Additional properties not allowed: url' on property change_password (Change Password page customization).
```
Explanation: the `default` value set for the `url` attribute in the JSON schema causes the validation logic to always add a `url` attribute set to `""` on …
=> fix: error for extra `url` when importing change_password

package-lock.json, package.json, src/auth0/handlers/guardianPhoneFactorMessageTypes.js, src/auth0/handlers/guardianPhoneFactorSelectedProvider.js, src/auth0/handlers/guardianPolicies.js, tests/auth0/handlers/guardianPhoneFactorMessageTypes.tests.js, tests/auth0/handlers/guardianPhoneFactorSelectedProvider.tests.js, tests/auth0/handlers/guardianPolicies.tests.js, tests/auth0/validator.tests.js
Fixes a bug introduced in https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/96.
#96 introduced support for guardian phone factor message types and phone factor selected provider, but given that the features are still in BETA, some customers might receive an HTTP `404` or HTTP `403` when calling the corresponding endpoint.
In this PR, we add some error handling that skips processing these settings if the management API returns one of these error conditions.
For guardian policies, I had to change the representation of the policies, going from an array of string to an object with a `policies` attribute.
Before:
```
guardianPolicies: ['all-applications']
```
After:
```
guardianPolicies: {
policies: ['all-applications']
}
```
This is to better handle the case when …
=> [MFA-351] fix(guardian): support for older installations

package-lock.json, package.json, src/auth0/handlers/index.js, src/auth0/handlers/migrations.js, src/auth0/handlers/pages.js, tests/auth0/handlers/migrations.tests.js, tests/auth0/validator.tests.js
Adds support for the new migrations endpoint. This is expected to be passed in the `migrations` property as a set of properties of type `boolean`.
When updating migrations the following checks are performed:
- The migration flags being set are compared with the migration flags available for the tenant at the moment of processing the import ([code](https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/97/files#diff-866ff42ac5a4faf805db4eb15fc0de0fR50)).
- If there are any migration flags that are not available. The behavior will depend on the value set for the flag:
- If the flag value is set to `false`, meaning that the migration is being disabled, we will log a *warning* and ignore the flag.
- if the flag value is set to `true`, meaning the migration is still …
=> feat(migrations): add support for migrations

package-lock.json, package.json, src/auth0/handlers/migrations.js, tests/auth0/handlers/migrations.tests.js
Fixes a bug introduced in #97
The `GET /api/v2/migrations` has recently been added to our Management API in cloud environments, but some PSaaS customers do not have that endpoint yet. For those customers, handle the HTTP `404` error by skipping processing of migrations (return an empty object).
⛔ 
Ticket = https://auth0team.atlassian.net/servicedesk/customer/portal/34/ESD-7469
Run deploy-cli 5.1.0 with an older PSaaS installation.
**Note to reviewers:** ensure that this change is compatible with the Appliance.
=> fix(migrations): handle 404 error for older installations

.github/PULL_REQUEST_TEMPLATE.md
Update the PR template to mention the special case of older PSaaS installation (they are usually lagging our cloud environments by at least a few weeks). For these environments, we need to ensure that any new handler gracefully handles when the endpoint has not yet been rolled out (and returns an HTTP 404 from our Management API). This PR adds a note the bring attention to this special case.
⛔ 
Related bugfix: https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/101
=> docs: add note about breaking older PSaaS installations

src/auth0/client.js, src/auth0/handlers/clientGrants.js, src/auth0/handlers/rulesConfigs.js, tests/auth0/validator.tests.js
The code to perform paginated requests was not being hit, since the proxy was defined in top of the client instead of the resource managers. This caused requests to be sent passing `paginate=true` to Management API, but no pagination was performed.
✅ This change has been tested in a Webtask
Has been tested on top of auth0-deploy-cli.
=> fix: using pagination for requests

package-lock.json, package.json, src/auth0/handlers/connections.js, src/auth0/handlers/databases.js, src/utils.js, tests/auth0/handlers/connections.tests.js, tests/auth0/handlers/databases.tests.js
For a client the connections are disabled when the client is added AUTH0_EXCLUDED_CLIENTS list.
This fix takes into account the existing connections for the client to decide if the connection should be enabled or disabled:
If the client is excluded and in the existing connection this client is enabled, it should keep enabled.
If the client is excluded and in the existing connection this client is disabled, it should keep disabled
https://auth0team.atlassian.net/browse/ESD-7795
=> [ESD-ESD-7795] fix disable connections

package-lock.json, package.json, src/utils.js, tests/auth0/handlers/clientGrants.tests.js, tests/utils.tests.js
In scenarios where multiple clients exist with the same name, and that client name was used in `AUTH0_EXCLUDED_CLIENTS`, the library was mistakenly deleting some Client Grants.
This was due to a utility function used to resolve names into IDs. When multiple clients with the same name existed, it only returned the `client_id` of the first client it encountered with a matching name, instead of returning all of the associated `client_id`s for a given client name. 
ESD-8476
=> Client grants fix

package-lock.json, package.json, src/auth0/handlers/connections.js, src/auth0/handlers/pages.js
- Fixed a call to `/connections` endpoint that missing the pagination parameter.
- Fixed a call to `/clients` endpoint that missing the pagination parameter.
- https://auth0team.atlassian.net/browse/DXEX-1038
User/client of this package should upgrade to the new release with this change
User/client of this package should downgrade to an earlier release known to work
=> [DXEX-1038] fix: use pagination in API calls 

package-lock.json, package.json, src/auth0/handlers/hooks.js, tests/auth0/handlers/hooks.tests.js
For hooks, 403 errors are being masked and an empty list is being returned. This fix changes the previous behaviour to report this errors as expected.
https://auth0team.atlassian.net/browse/ESD-9513
=> [ESD-9513] a0deploy hooks export failed but no error reported

package-lock.json, package.json, src/constants.js
⚠️ This is identical to #123, but back-porting to v4.x branch ⚠️ 
Add a new email template key `verify_email_by_code`, to support the "Verification Email (using Code)" template that was introduced in the past few months in the dashboard:
This is required in order to address the issue reported here: https://github.com/auth0/auth0-deploy-cli/issues/303
⚠️ this will require a version bump of auth0-source-control-extension-tools in https://github.com/auth0/auth0-deploy-cli
https://auth0team.atlassian.net/browse/CAUTH-837
=> [CAUTH-837] add support for `verify_email_by_code` email template (v4.x)

package-lock.json, package.json, src/auth0/client.js, tests/auth0/client.tests.js
Deep clone args for pagination to prevent further modifications. This prevents some bugs happening with a large set of entities that needs to go through pagination.
https://auth0team.atlassian.net/browse/ESD-12159
✅ This change has been tested for performance
=> [ESD-12159] Fix pagination

src/constants.js, tests/auth0/handlers/guardianFactors.tests.js
Adding support for webauthn-platform factor.
I followed the example of https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/115
https://auth0team.atlassian.net/browse/MFA-997
=> MFA-997 Add webauthn platform as a supported factor

package.json, src/auth0/handlers/index.js, src/auth0/handlers/organizations.js, tests/auth0/handlers/organizations.tests.js
Added Organizations support. With organizations, we export also their connections. Invites, organization members are not included as we currently don't export user related data
=> Add support for Organizations Feature

src/constants.js
This PR adds `user-invitation` email template type to whitelist. The template type is supported by auth0 management API but not whitelisted in the extension-tools. 
https://auth0.com/docs/api/management/v2?_ga=2.78377239.2071533785.1617019012-783567391.1598615059#!/Email_Templates/get_email_templates_by_templateName
=> feat: whitelist user-invitation email template

src/auth0/handlers/connections.js, src/auth0/handlers/organizations.js, tests/auth0/handlers/organizations.tests.js
I was storying the enabled connection entity as is and it worked fine, but I realized that keeping the ID is problematic when a customer wants to add a new connection (yeah, that is obvious now :P ). So now I store the connection name as part of the organization and when importing it, I need to search the connection that matches that name and use the id
Old
```
organizations:
- name: acme
connections:
- connection_id: con_123
assign_membership_on_login: false
display_name: Acme Inc
metadata:
account: 123_abc
```
New
```
organizations:
- name: acme
connections:
- name: db
assign_membership_on_login: false
display_name: Acme Inc
metadata:
account: 123_abc
```
✅ This …
=> Fixed enabled connections logic

package-lock.json, package.json, src/auth0/handlers/connections.js
Before this fix, when the enabled_clients field inside a connection is undefined, it was changed by an empty list, this had as a consequence that all the enabled clients for the connections were deleted.
https://auth0team.atlassian.net/browse/ESD-12815
This fix was tested locally
✅. This can be deployed any time
=> [ESD-12815] Fix excluded enabled clients

package-lock.json, package.json, src/constants.js, tests/auth0/handlers/guardianFactors.tests.js
Updating the allowed factors to support optional recovery codes in our upcoming feature
https://auth0team.atlassian.net/browse/MFA-1088
Testing e2e in vivaldi with deploy cli 
I believe this can be merged anytime, but the version bump in auth0 deploy cli might need to wait
✅🚫 This can be deployed any time
=> MFA-1174 Support Recovery Codes
