src/auth0/rules.js
tests/auth0/connections.tests.js
tests/auth0/rules.tests.js

- updateRules fixed
- unit-tests extended

Silent failure

---

README.md
package.json
src/auth0/clients.js
src/auth0/index.js
src/auth0/pages.js
src/auth0/rules.js
src/constants.js
src/deploy.js
src/index.js
src/slack.js
src/utils.js
tests/auth0/clients.tests.js
tests/mocha.js
tests/slack.tests.js
tests/utils.tests.js

This adds a fairly basic ability to add and update clients.  It won't do anything if you don't pass in any clients.

mostekcm add client deploy capability

---

package.json
src/auth0/clients.js
src/auth0/configurables.js
src/auth0/connections.js
src/auth0/index.js
src/auth0/resourceServers.js
src/constants.js
src/deploy.js
src/slack.js
tests/auth0/clients.tests.js
tests/auth0/configurables.tests.js
tests/auth0/connections.tests.js
tests/auth0/resourceServers.tests.js
tests/slack.tests.js

This is the pull request to add resource servers and client grants.
The client grants are done as part of the meta data for the client.  This greatly reduces the areas for errors as it enforces the existence of a client and only allows audience/scope pairs.

Mostekcm add apps and client grants

---

src/auth0/clients.js
tests/auth0/clients.tests.js

Fixes bug: https://github.com/auth0-extensions/auth0-source-control-extension-tools/issues/9

Fixes bug with client grants

---

src/auth0/index.js
src/auth0/ruleConfigs.js
src/constants.js
src/deploy.js
src/webhook.js

Tested this build on all deploy extensions. Clients, resource-servers and rules-configs deploy is working fine.

Rule configs

---

.eslintrc
src/auth0/connections.js
src/auth0/multipartRequest.js
src/auth0/pages.js
tests/auth0/pages.tests.js

Allow for the configuration of the url in error_page.
Fixed some linting errors (also allow ++ at the end of for () statement

Error page url

---

src/auth0/connections.js
src/auth0/databaseConnections.js
src/auth0/index.js
src/constants.js
src/deploy.js
tests/auth0/configurables.tests.js
tests/auth0/connections.tests.js
tests/auth0/database-connections.tests.js
tests/storage.tests.js

Renamed internal classes related to database`connections` to `databaseConnections`.
Created new `connections` classes, to support `create` and `update` opperations for _connections_.

Add support for Connections

---

package-lock.json
package.json
src/auth0/index.js

Better error logging. Allow tool to handle the error reporting.

Allow tool to handle the error reporting.

---

package.json
src/auth0/handlers/default.js
src/deploy.js
src/logger.js

Add more logging and fix error on processchanges when del is not set.

Add more logging and fix error on processchanges when del is not set.

---

src/auth0/handlers/pages.js

Fix issue where login page exported as undefined if not set.

Update Login page undefined if not set

---

src/auth0/handlers/clientGrants.js
src/auth0/handlers/clients.js
src/auth0/handlers/connections.js
src/auth0/handlers/databases.js
src/auth0/handlers/emailTemplates.js
src/auth0/handlers/guardianFactorProviders.js
src/auth0/handlers/guardianFactorTemplates.js
src/auth0/handlers/guardianFactors.js
src/auth0/handlers/pages.js
src/auth0/handlers/resourceServers.js

There was a bug in the `validation` step. Just fixing schemas in this change.
Slack: https://auth0.slack.com/archives/C9170558S/p1547134385102300
✅ This change has been tested locally

fixed 'required' prop of hanlers schemas

---

src/auth0/handlers/clientGrants.js
src/auth0/handlers/databases.js
src/auth0/handlers/rulesConfigs.js

Quick fix for other problems found with schema validator.

Fix schema errors

---

src/auth0/handlers/clientGrants.js
src/auth0/handlers/connections.js
src/auth0/handlers/emailTemplates.js
src/auth0/handlers/pages.js
src/auth0/handlers/rules.js
src/auth0/handlers/rulesConfigs.js
tests/auth0/validator.tests.js

Few minor fixes and tests for all those schemas.
Slack: https://auth0.slack.com/archives/C9170558S/p1547483216119800

added tests for schema validation

---

src/auth0/handlers/databases.js
tests/auth0/validator.tests.js

Fix for databases options schema. Tests updated.

removed unnecessary required fields from databases.options schema

---

src/auth0/handlers/databases.js
tests/auth0/handlers/clientGrants.tests.js
tests/auth0/handlers/clients.tests.js
tests/auth0/handlers/connections.tests.js
tests/auth0/handlers/databases.tests.js
tests/auth0/handlers/resourceServers.tests.js
tests/auth0/handlers/rules.tests.js

Same as #59, but for databases. Somehow i missed database handler in previous PR. Sorry 🥺 
Github issue: https://github.com/auth0/auth0-deploy-cli/issues/74
Github PR comment: https://github.com/auth0/auth0-deploy-cli/pull/89#issuecomment-466565983
✅ This change has been tested locally

Process empty array of databases (KEY-686)

---

README.md
package.json
src/auth0/handlers/clients.js
tests/auth0/handlers/clients.tests.js

Same as excluded rules, but for clients.
Jira: https://auth0team.atlassian.net/browse/KEY-824

KEY-824: excluded clients

---

src/auth0/handlers/branding.js
src/auth0/handlers/index.js
src/auth0/handlers/prompts.js
tests/auth0/handlers/branding.tests.js
tests/auth0/handlers/prompts.tests.js
tests/auth0/validator.tests.js

This supports downstream updates to https://github.com/auth0/node-auth0 and https://github.com/auth0-extensions/auth0-extension-tools
* https://github.com/auth0/node-auth0/pull/370
* https://github.com/auth0-extensions/auth0-extension-tools/pull/16
Unit tests included.
🚫 This change has been tested in a Webtask 

Add handlers for the Branding and Prompts Management API endpoints.

---

package-lock.json
package.json
src/auth0/handlers/branding.js
src/auth0/handlers/clientGrants.js
src/auth0/handlers/connections.js
src/auth0/handlers/databases.js
src/auth0/handlers/prompts.js
src/auth0/handlers/roles.js
src/utils.js
tests/auth0/handlers/clientGrants.tests.js
tests/auth0/handlers/connections.tests.js
tests/auth0/handlers/databases.tests.js
tests/auth0/handlers/rules.tests.js
tests/utils.tests.js

- Allow excluding `connections`/`databases`.
- Ignore `clientGrants` of excluded `clients`.
- Handle `501 Not Implemented` errors for `branding` and `roles`.
I also need this added to webtask to use with deploy-extensions.

More excludes

---

package-lock.json
src/auth0/handlers/hooks.js
src/auth0/handlers/index.js
src/constants.js

[DXEX-222] create hook

---

src/auth0/handlers/roles.js

The previous approach for this handler was more likely to trigger rate limit related errors as certain roles operations would be queued all at once. With this update the operations are spread a bit more evenly and should reduce the likelihood of global rate limit errors.
https://auth0team.atlassian.net/browse/ESD-8299
The existing tests for roles creation. 
✅  This change has unit test coverage

[ESD-8299]Update roles handler to use pool executor client

---

src/constants.js
tests/auth0/handlers/guardianFactors.tests.js
tests/auth0/validator.tests.js

adding webauth-roaming as valid MFA factor name
https://auth0team.atlassian.net/browse/ESD-10050

[ESD-10050] add webauth-roaming as valid MFA factor name

---

package-lock.json
package.json

[ESD-10050] bump version to 4.1.10

---

package-lock.json
package.json
src/constants.js
tests/auth0/handlers/guardianFactors.tests.js

fix MFA factor name typo
https://auth0team.atlassian.net/browse/ESD-10050

[ESD-10050] fix MFA factor name typo

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Update release notes and PR template
n/a
n/a
n/a

chore: 5.x release notes and update PR template

---

package-lock.json
package.json
src/auth0/handlers/actionBindings.js
src/auth0/handlers/actionVersions.js
src/auth0/handlers/actions.js
src/auth0/handlers/index.js
src/constants.js
src/utils.js
tests/auth0/handlers/actions.tests.js
tests/auth0/handlers/guardianFactors.tests.js

Adds support for the new actions endpoint.
Action handler uses actionVersioHandler and actionBindingHandler to be able to manages those as part of an action.
https://auth0team.atlassian.net/browse/DXEX-714
🚫   This change has been tested in a Webtask
✅  This change has unit test coverage
🚫  This change has integration test coverage

add support for Actions

---

package-lock.json
package.json
src/constants.js
tests/auth0/handlers/guardianFactors.tests.js

Porting change to v4 branch.
> Include at at least one link to an explanation + requirements for this change, and more if at all possible. Typically this is a Jira/GitHub Issue, but could also be links to Zendesk tickets, RFCs, rollout plan or Slack conversations (for Slack conversations, make sure you provide a summary of the conversation under “Changes”).
> Describe how this can be tested by reviewers. Please be specific about anything not tested and reasons why.
> - Make sure you add unit and integration tests.
✅🚫 This change has unit test coverage
✅🚫 This change has integration test coverage
✅🚫 This change has been tested …

Fix webauthn platform

---

package-lock.json
package.json
src/auth0/client.js
src/auth0/handlers/roles.js
tests/auth0/client.tests.js
tests/auth0/handlers/roles.tests.js

Remove 50 limit on roles.permissions
https://auth0team.atlassian.net/secure/RapidBoard.jspa?rapidView=439&projectKey=DXEX&modal=detail&selectedIssue=ESD-7536
> Describe how this can be tested by reviewers. Please be specific about anything not tested and reasons why.
> - Make sure you add unit and integration tests.
✅ This change has been tested for performance

[ESD-7536] fix: export all permissions for a role (v4)

---

package-lock.json
package.json
src/auth0/client.js
src/auth0/handlers/roles.js
tests/auth0/client.tests.js
tests/auth0/handlers/roles.tests.js

Remove 50 limit on roles.permissions
https://auth0team.atlassian.net/secure/RapidBoard.jspa?rapidView=439&projectKey=DXEX&modal=detail&selectedIssue=ESD-7536
> Describe how this can be tested by reviewers. Please be specific about anything not tested and reasons why.
> - Make sure you add unit and integration tests.
✅ This change has been tested for performance

[ESD-7536] fix: export all permissions for a role (v5)

---

package-lock.json
package.json
src/auth0/handlers/index.js
src/auth0/handlers/organizations.js
tests/auth0/handlers/organizations.tests.js

[4.x] Merge pull request #135 from mcastany/organizations-support

---

package-lock.json
package.json
src/constants.js

Backport #137 to v4.x

---

src/auth0/handlers/organizations.js

Fix issue with pagination. Applied feedback in earlier PR but I've just tested the E2E experience and the value in the feedback was wrong. The flag is paginate, not pagination :fp:
https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/af0166baeefa3a1a1ec74dae82329956ad19bfa7/src/auth0/client.js#L28
Previous PR: https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/135#discussion_r597148607
Manually tested it with deploy-cli and it works

Fixed issue with pagination

---

package-lock.json
package.json
src/utils.js

fix undefined arrays in areArraysEqual
> Describe how this can be tested by reviewers. Please be specific about anything not tested and reasons why.
> - Make sure you add unit and integration tests.
✅🚫 This change has unit test coverage
✅🚫 This change has integration test coverage
✅🚫 This change has been tested for performance
✅This can be deployed any time

fix undefined arrays

---

package-lock.json
package.json
src/auth0/handlers/actions.js
src/auth0/handlers/triggers.js
tests/auth0/handlers/actions.tests.js

- adding deployed field
- remove current_version from schema
- create version and update draft version on code or dependencies changes
- set default runtime as "node12"
- return `null` objects on 404 or 501
> Include at at least one link to an explanation + requirements for this change, and more if at all possible. Typically this is a Jira/GitHub Issue, but could also be links to Zendesk tickets, RFCs, rollout plan or Slack conversations (for Slack conversations, make sure you provide a summary of the conversation under “Changes”).
✅🚫 This change has integration test coverage
✅🚫 This change has been tested for performance
✅. This can be deployed any time

removing current_version from action result

---

package-lock.json
package.json
src/auth0/handlers/actions.js
tests/auth0/handlers/actions.tests.js

update actions for the last API2 changes
https://auth0team.atlassian.net/browse/DXEX-1467
✅🚫 This change has been tested for performance

[DXEX-1467] update actions for the API2 changes

---

package-lock.json
package.json
src/auth0/handlers/actions.js
src/auth0/handlers/triggers.js
tests/auth0/handlers/actions.tests.js
tests/auth0/handlers/triggers.tests.js

Skip actions if `api2_enable_actions` is not enabled. Sorry for the prettier noise. I added comments by all the functional changes.
https://auth0team.atlassian.net/browse/DXEX-1454

Skip actions if api2_enable_actions is not enabled

---

src/auth0/handlers/actions.js

Actions code was not waiting async.

Fix for actions as it wasn't waiting async.

---

package-lock.json
package.json
src/constants.js
tests/auth0/handlers/guardianFactors.tests.js

Updating the allowed factors to support optional recovery codes in our upcoming feature
https://auth0team.atlassian.net/browse/MFA-1088
Testing e2e in vivaldi with deploy cli 
I believe this can be merged anytime, but the version bump in auth0 deploy cli might need to wait
✅🚫 This can be deployed any time

MFA-1174 Support Recovery Codes
